---
require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  NewCops: enable
  Exclude:
    - 'spec/fixtures/**/*'
    - vendor/bundle/**/*

Layout/LineLength:
  Enabled: false

Style/CommandLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/RedundantInterpolation:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline
