---
name: Test & Lint

on:
  push:
    branches-ignore:
      - 'test/*'
  pull_request:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"

    steps:
      - uses: actions/checkout@v3

      - name: Set up ruby ({{ matrix.ruby }})
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: bundle exec rake
